{"name": "有效等价类+边界值: a, b", "status": "broken", "statusDetails": {"message": "TypeError: '>' not supported between instances of 'str' and 'int'", "trace": "self = <case.pytest_allure.testcase.test_div.TestDiv object at 0x10e08e980>\nx = 'a', y = 'b', expected = '参数大小超出范围'\ncalculator = <case.pytest_allure.func.calculator.Calculator object at 0x10e08fd60>\n\n    @pytest.mark.no_valid\n    @allure.title(\"有效等价类+边界值: {x}, {y}\")\n    @pytest.mark.parametrize(\"x, y, expected\", get_data(\"no_valid\"))\n    def test_02(self, x, y, expected, calculator):\n        logging.info(f\"无效等价类{x}, {y}\")\n>       assert calculator.div(x, y) == expected\n\ntestcase/test_div.py:46: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <case.pytest_allure.func.calculator.Calculator object at 0x10e08fd60>\na = 'a', b = 'b'\n\n    def div(self, a, b):\n>       if a > 99 or a < -99 or b > 99 or b < -99:\nE       TypeError: '>' not supported between instances of 'str' and 'int'\n\nfunc/calculator.py:10: TypeError"}, "attachments": [{"name": "log", "source": "00deae11-e560-43ef-820f-d2f1c00adbc1-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "x", "value": "'a'"}, {"name": "y", "value": "'b'"}, {"name": "expected", "value": "'参数大小超出范围'"}], "start": 1683126183636, "stop": 1683126183636, "uuid": "3d67503f-8caa-4d4c-8927-04ec4a552d75", "historyId": "b47263c8dbb2a56ad07b1103bf11a46e", "testCaseId": "3eb860cfc3e99e9ac7d5390a7d7e4513", "fullName": "testcase.test_div.TestDiv#test_02", "labels": [{"name": "tag", "value": "no_valid"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_div"}, {"name": "subSuite", "value": "TestDiv"}, {"name": "host", "value": "AnndeMacBook-Pro-2.local"}, {"name": "thread", "value": "14644-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_div"}]}